codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...95"
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 5%
        informational: true
