//! Structured JSON generator using `arbitrary` for coverage-guided fuzzing.
//!
//! Generates syntactically valid JSON with controllable depth and size,
//! enabling the fuzzer to explore deep parsing paths instead of getting
//! stuck on syntax errors.

use std::fmt::Write;

use arbitrary::{Arbitrary, Unstructured};

/// Maximum recursion depth for nested structures.
const MAX_DEPTH: u8 = 32;
/// Maximum number of elements in arrays/objects per level.
const MAX_CONTAINER_LEN: u8 = 16;

/// A structured JSON value that can be generated by `arbitrary`.
#[derive(Debug, Clone)]
pub enum JsonValue {
    Null,
    Bool(bool),
    Int(i64),
    Uint(u64),
    Float(f64),
    Str(JsonString),
    Array(Vec<JsonValue>),
    Object(Vec<(JsonString, JsonValue)>),
}

/// A string value with controlled escape patterns.
#[derive(Debug, Clone, Arbitrary)]
pub enum JsonString {
    /// Plain ASCII string (no escapes needed).
    Ascii(AsciiStr),
    /// String with embedded escape sequences.
    WithEscapes(EscapeStr),
    /// String with unicode characters.
    Unicode(UnicodeStr),
    /// Empty string.
    Empty,
}

#[derive(Debug, Clone)]
pub struct AsciiStr(pub String);

#[derive(Debug, Clone)]
pub struct EscapeStr(pub String);

#[derive(Debug, Clone)]
pub struct UnicodeStr(pub String);

impl<'a> Arbitrary<'a> for AsciiStr {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        let len = u.int_in_range(0..=64)?;
        let mut s = String::with_capacity(len);
        for _ in 0..len {
            // Printable ASCII excluding \ and "
            let c = u.int_in_range(0x20u8..=0x7E)?;
            if c == b'\\' || c == b'"' {
                s.push('a');
            } else {
                s.push(c as char);
            }
        }
        Ok(AsciiStr(s))
    }
}

impl<'a> Arbitrary<'a> for EscapeStr {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        let len = u.int_in_range(1..=32)?;
        let mut s = String::with_capacity(len * 2);
        for _ in 0..len {
            let choice: u8 = u.int_in_range(0..=9)?;
            match choice {
                0 => s.push_str("\\n"),
                1 => s.push_str("\\t"),
                2 => s.push_str("\\r"),
                3 => s.push_str("\\\\"),
                4 => s.push_str("\\/"),
                5 => s.push_str("\\\""),
                6 => s.push_str("\\b"),
                7 => s.push_str("\\f"),
                8 => {
                    // \uXXXX with valid codepoint
                    let cp: u16 = u.int_in_range(0x0020..=0x007E)?;
                    write!(s, "\\u{:04X}", cp).unwrap();
                }
                _ => {
                    // Surrogate pair
                    let hi: u16 = u.int_in_range(0xD800..=0xDBFF)?;
                    let lo: u16 = u.int_in_range(0xDC00..=0xDFFF)?;
                    write!(s, "\\u{:04X}\\u{:04X}", hi, lo).unwrap();
                }
            }
        }
        Ok(EscapeStr(s))
    }
}

impl<'a> Arbitrary<'a> for UnicodeStr {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        let len = u.int_in_range(1..=16)?;
        let mut s = String::with_capacity(len * 4);
        for _ in 0..len {
            let choice: u8 = u.int_in_range(0..=3)?;
            match choice {
                0 => s.push('\u{00E9}'),  // e-acute (2-byte UTF-8)
                1 => s.push('\u{4E2D}'),  // CJK character (3-byte UTF-8)
                2 => s.push('\u{1F600}'), // emoji (4-byte UTF-8)
                _ => {
                    let cp = u.int_in_range(0x80u32..=0x07FF)?;
                    if let Some(c) = char::from_u32(cp) {
                        s.push(c);
                    } else {
                        s.push('\u{00E9}');
                    }
                }
            }
        }
        Ok(UnicodeStr(s))
    }
}

impl JsonString {
    /// Write this string as a JSON-encoded string (with surrounding quotes).
    pub fn write_json(&self, out: &mut String) {
        out.push('"');
        match self {
            JsonString::Ascii(AsciiStr(s)) => out.push_str(s),
            JsonString::WithEscapes(EscapeStr(s)) => out.push_str(s), // already escaped
            JsonString::Unicode(UnicodeStr(s)) => {
                // Need to JSON-escape the UTF-8 string
                for c in s.chars() {
                    match c {
                        '"' => out.push_str("\\\""),
                        '\\' => out.push_str("\\\\"),
                        c if (c as u32) < 0x20 => {
                            write!(out, "\\u{:04X}", c as u32).unwrap();
                        }
                        c => out.push(c),
                    }
                }
            }
            JsonString::Empty => {}
        }
        out.push('"');
    }

    /// Return the raw string content (for use as object key, etc).
    pub fn as_raw(&self) -> &str {
        match self {
            JsonString::Ascii(AsciiStr(s)) => s,
            JsonString::WithEscapes(EscapeStr(s)) => s,
            JsonString::Unicode(UnicodeStr(s)) => s,
            JsonString::Empty => "",
        }
    }
}

/// Internal helper to generate JsonValue with bounded depth.
fn arbitrary_value<'a>(u: &mut Unstructured<'a>, depth: u8) -> arbitrary::Result<JsonValue> {
    if depth >= MAX_DEPTH || u.is_empty() {
        // At max depth, only generate scalars
        let choice: u8 = u.int_in_range(0..=4)?;
        return Ok(match choice {
            0 => JsonValue::Null,
            1 => JsonValue::Bool(u.arbitrary()?),
            2 => JsonValue::Int(u.arbitrary()?),
            3 => JsonValue::Uint(u.arbitrary()?),
            _ => JsonValue::Str(u.arbitrary()?),
        });
    }

    let choice: u8 = u.int_in_range(0..=7)?;
    Ok(match choice {
        0 => JsonValue::Null,
        1 => JsonValue::Bool(u.arbitrary()?),
        2 => JsonValue::Int(u.arbitrary()?),
        3 => JsonValue::Uint(u.arbitrary()?),
        4 => {
            let f: f64 = u.arbitrary()?;
            if f.is_finite() {
                JsonValue::Float(f)
            } else {
                JsonValue::Null
            }
        }
        5 => JsonValue::Str(u.arbitrary()?),
        6 => {
            let len: u8 = u.int_in_range(0..=MAX_CONTAINER_LEN)?;
            let mut arr = Vec::with_capacity(len as usize);
            for _ in 0..len {
                if u.is_empty() {
                    break;
                }
                arr.push(arbitrary_value(u, depth + 1)?);
            }
            JsonValue::Array(arr)
        }
        _ => {
            let len: u8 = u.int_in_range(0..=MAX_CONTAINER_LEN)?;
            let mut obj = Vec::with_capacity(len as usize);
            for _ in 0..len {
                if u.is_empty() {
                    break;
                }
                let key: JsonString = u.arbitrary()?;
                let val = arbitrary_value(u, depth + 1)?;
                obj.push((key, val));
            }
            JsonValue::Object(obj)
        }
    })
}

impl<'a> Arbitrary<'a> for JsonValue {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        arbitrary_value(u, 0)
    }
}

impl JsonValue {
    /// Serialize to a JSON string.
    pub fn to_json(&self) -> String {
        let mut out = String::with_capacity(256);
        self.write_json(&mut out);
        out
    }

    fn write_json(&self, out: &mut String) {
        match self {
            JsonValue::Null => out.push_str("null"),
            JsonValue::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
            JsonValue::Int(n) => write!(out, "{}", n).unwrap(),
            JsonValue::Uint(n) => write!(out, "{}", n).unwrap(),
            JsonValue::Float(f) => {
                write!(out, "{}", f).unwrap();
            }
            JsonValue::Str(s) => s.write_json(out),
            JsonValue::Array(arr) => {
                out.push('[');
                for (i, v) in arr.iter().enumerate() {
                    if i > 0 {
                        out.push(',');
                    }
                    v.write_json(out);
                }
                out.push(']');
            }
            JsonValue::Object(obj) => {
                out.push('{');
                for (i, (k, v)) in obj.iter().enumerate() {
                    if i > 0 {
                        out.push(',');
                    }
                    k.write_json(out);
                    out.push(':');
                    v.write_json(out);
                }
                out.push('}');
            }
        }
    }

    /// Collect all object keys in this value (recursively).
    pub fn collect_keys(&self, keys: &mut Vec<String>) {
        match self {
            JsonValue::Object(obj) => {
                for (k, v) in obj {
                    keys.push(k.as_raw().to_string());
                    v.collect_keys(keys);
                }
            }
            JsonValue::Array(arr) => {
                for v in arr {
                    v.collect_keys(keys);
                }
            }
            _ => {}
        }
    }

    /// Get the nesting depth.
    pub fn depth(&self) -> usize {
        match self {
            JsonValue::Array(arr) => 1 + arr.iter().map(|v| v.depth()).max().unwrap_or(0),
            JsonValue::Object(obj) => 1 + obj.iter().map(|(_, v)| v.depth()).max().unwrap_or(0),
            _ => 0,
        }
    }
}

/// Input for number-focused fuzzing.
#[derive(Debug, Arbitrary)]
pub struct NumberInput {
    /// The numeric pattern to test.
    pub pattern: NumberPattern,
    /// Whether to add surrounding JSON context.
    pub in_array: bool,
}

#[derive(Debug, Arbitrary)]
pub enum NumberPattern {
    /// Plain integer with controlled digit count.
    Integer { negative: bool, digits: DigitCount },
    /// Floating point with controlled parts.
    Floating {
        negative: bool,
        integer_digits: DigitCount,
        fraction_digits: DigitCount,
    },
    /// Scientific notation.
    Scientific {
        negative: bool,
        integer_digits: DigitCount,
        fraction_digits: DigitCount,
        exp_negative: bool,
        exp_value: u16,
    },
    /// Edge case numbers.
    Edge(NumberEdge),
    /// Raw bytes that might be a number.
    Raw(RawNumber),
}

#[derive(Debug, Arbitrary)]
pub enum DigitCount {
    One,
    Few,      // 2-4
    Medium,   // 5-8 (SWAR boundary)
    Long,     // 9-16 (double SWAR)
    VeryLong, // 17-20 (u64 overflow boundary)
}

#[derive(Debug, Arbitrary)]
pub enum NumberEdge {
    Zero,
    NegZero,
    MaxU64,
    MinI64,
    MaxI64,
    MaxU64Plus1,
    MinI64Minus1,
    F64MaxInt,        // 2^53
    F64MaxIntPlus1,   // 2^53 + 1
    VerySmallFloat,   // 0.000...001
    LeadingZeroFloat, // 0.123
    F32DisguisedFastPath,
    F32TieBoundary,
    F32MaxFinite,
    F32Overflow,
    ManyDigits, // 100+ digits
}

#[derive(Debug)]
pub struct RawNumber(pub Vec<u8>);

impl<'a> Arbitrary<'a> for RawNumber {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        let len = u.int_in_range(1..=32)?;
        let mut bytes = Vec::with_capacity(len);
        let charset = b"0123456789.eE+-";
        for _ in 0..len {
            let idx = u.int_in_range(0..=charset.len() - 1)?;
            bytes.push(charset[idx]);
        }
        Ok(RawNumber(bytes))
    }
}

impl NumberInput {
    /// Generate the JSON bytes for this number input.
    pub fn to_json_bytes(&self) -> Vec<u8> {
        let num = self.pattern.to_string();
        if self.in_array {
            format!("[{}]", num).into_bytes()
        } else {
            num.into_bytes()
        }
    }
}

impl NumberPattern {
    pub fn to_string(&self) -> String {
        match self {
            NumberPattern::Integer { negative, digits } => {
                let sign = if *negative { "-" } else { "" };
                let n = match digits {
                    DigitCount::One => "7".to_string(),
                    DigitCount::Few => "1234".to_string(),
                    DigitCount::Medium => "12345678".to_string(),
                    DigitCount::Long => "1234567890123456".to_string(),
                    DigitCount::VeryLong => "18446744073709551615".to_string(), // u64::MAX
                };
                format!("{}{}", sign, n)
            }
            NumberPattern::Floating {
                negative,
                integer_digits,
                fraction_digits,
            } => {
                let sign = if *negative { "-" } else { "" };
                let int_part = match integer_digits {
                    DigitCount::One => "3",
                    DigitCount::Few => "1234",
                    DigitCount::Medium => "12345678",
                    DigitCount::Long => "1234567890123456",
                    DigitCount::VeryLong => "12345678901234567890",
                };
                let frac_part = match fraction_digits {
                    DigitCount::One => "5",
                    DigitCount::Few => "1234",
                    DigitCount::Medium => "12345678",
                    DigitCount::Long => "1234567890123456",
                    DigitCount::VeryLong => "12345678901234567890",
                };
                format!("{}{}.{}", sign, int_part, frac_part)
            }
            NumberPattern::Scientific {
                negative,
                integer_digits,
                fraction_digits,
                exp_negative,
                exp_value,
            } => {
                let sign = if *negative { "-" } else { "" };
                let int_part = match integer_digits {
                    DigitCount::One => "3",
                    _ => "12345678",
                };
                let frac_part = match fraction_digits {
                    DigitCount::One => "5",
                    _ => "12345678",
                };
                let exp_sign = if *exp_negative { "-" } else { "+" };
                format!(
                    "{}{}.{}e{}{}",
                    sign, int_part, frac_part, exp_sign, exp_value
                )
            }
            NumberPattern::Edge(edge) => match edge {
                NumberEdge::Zero => "0".to_string(),
                NumberEdge::NegZero => "-0".to_string(),
                NumberEdge::MaxU64 => "18446744073709551615".to_string(),
                NumberEdge::MinI64 => "-9223372036854775808".to_string(),
                NumberEdge::MaxI64 => "9223372036854775807".to_string(),
                NumberEdge::MaxU64Plus1 => "18446744073709551616".to_string(),
                NumberEdge::MinI64Minus1 => "-9223372036854775809".to_string(),
                NumberEdge::F64MaxInt => "9007199254740992".to_string(),
                NumberEdge::F64MaxIntPlus1 => "9007199254740993".to_string(),
                NumberEdge::VerySmallFloat => "0.00000000000000001".to_string(),
                NumberEdge::LeadingZeroFloat => "0.123456789012345678".to_string(),
                NumberEdge::F32DisguisedFastPath => "100e11".to_string(),
                NumberEdge::F32TieBoundary => "17005001.000000000000130".to_string(),
                NumberEdge::F32MaxFinite => "3.4028235e38".to_string(),
                NumberEdge::F32Overflow => "3.4028236e38".to_string(),
                NumberEdge::ManyDigits => {
                    let mut s = String::with_capacity(120);
                    for _ in 0..110 {
                        s.push('9');
                    }
                    s
                }
            },
            NumberPattern::Raw(raw) => String::from_utf8_lossy(&raw.0).to_string(),
        }
    }
}

/// Input for deep nesting focused fuzzing.
#[derive(Debug, Arbitrary)]
pub struct DeepNestInput {
    pub pattern: NestPattern,
}

#[derive(Debug, Arbitrary)]
pub enum NestPattern {
    /// Deeply nested arrays: [[[[...]]]]
    DeepArray { depth: u16 },
    /// Deeply nested objects: {"a":{"a":{...}}}
    DeepObject { depth: u16 },
    /// Wide array with many elements
    WideArray { count: u16 },
    /// Wide object with many keys
    WideObject { count: u16 },
    /// Mixed deep nesting with values at each level
    Mixed { depth: u16, width: u8 },
}

impl DeepNestInput {
    pub fn to_json(&self) -> String {
        match &self.pattern {
            NestPattern::DeepArray { depth } => {
                let d = (*depth).min(512) as usize;
                let mut s = String::with_capacity(d * 2 + 4);
                for _ in 0..d {
                    s.push('[');
                }
                s.push_str("null");
                for _ in 0..d {
                    s.push(']');
                }
                s
            }
            NestPattern::DeepObject { depth } => {
                let d = (*depth).min(512) as usize;
                let mut s = String::with_capacity(d * 8 + 4);
                for i in 0..d {
                    if i > 0 {
                        s.push(',');
                    }
                    s.push_str("{\"k\":");
                }
                s.push_str("null");
                for _ in 0..d {
                    s.push('}');
                }
                s
            }
            NestPattern::WideArray { count } => {
                let c = (*count).min(4096) as usize;
                let mut s = String::with_capacity(c * 3 + 2);
                s.push('[');
                for i in 0..c {
                    if i > 0 {
                        s.push(',');
                    }
                    // Alternate value types
                    match i % 5 {
                        0 => s.push_str("null"),
                        1 => s.push_str("true"),
                        2 => write!(s, "{}", i).unwrap(),
                        3 => write!(s, "\"s{}\"", i).unwrap(),
                        _ => s.push_str("false"),
                    }
                }
                s.push(']');
                s
            }
            NestPattern::WideObject { count } => {
                let c = (*count).min(4096) as usize;
                let mut s = String::with_capacity(c * 12 + 2);
                s.push('{');
                for i in 0..c {
                    if i > 0 {
                        s.push(',');
                    }
                    write!(s, "\"key{}\":{}", i, i).unwrap();
                }
                s.push('}');
                s
            }
            NestPattern::Mixed { depth, width } => {
                let d = (*depth).min(256) as usize;
                let w = (*width).min(8) as usize;
                let mut s = String::with_capacity(d * w * 8);
                build_mixed(&mut s, d, w);
                s
            }
        }
    }
}

fn build_mixed(out: &mut String, depth: usize, width: usize) {
    if depth == 0 {
        out.push_str("42");
        return;
    }
    out.push('[');
    for i in 0..width {
        if i > 0 {
            out.push(',');
        }
        if i % 2 == 0 {
            build_mixed(out, depth - 1, width);
        } else {
            out.push('{');
            write!(out, "\"v\":").unwrap();
            build_mixed(out, depth - 1, width);
            out.push('}');
        }
    }
    out.push(']');
}
